chore: deps update
storyblok/storyblok-vue pull request #247
Opened 2023-03-31 08:51 UTC by alvarosabu

2023-03-31 09:15 UTC, Dawntraoz commented on lib/tsconfig.json
> +    "ignoreDeprecations": "5.0"
Oh, so this was the fix to the broken CI? I'm curious to know what happened. Good catch <3

2023-03-31 09:15 UTC, Dawntraoz approved these changes

2023-03-31 09:18 UTC, Dawntraoz requested changes
I see what you did there 😏, but would it be better to fix the issue before 5.5 comes in and stop working?

> Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

2023-04-03 06:44 UTC, alvarosabu commented
> importsNotUsedAsValues

That would have been my preferred option, but `importsNotUsedAsValues` is not even set on non of the tsconfigs of our repository (if you try to search for it on the repo you will not find it)

2023-04-03 06:59 UTC, alvarosabu commented
@alexjoverm @Dawntraoz seems like the warning comes from this line on the tsconfig

```
 "extends": "@vue/tsconfig/tsconfig.json"
```
<img width="929" alt="Screenshot 2023-04-03 at 08 54 51" src="https://user-images.githubusercontent.com/4699008/229433553-cdfa06b1-01ea-4d10-8018-59cf70f6e508.png">

Seems like `@vue` package hasn't replace `importsNotUsedAsValues` and `preserveValueImports`  with `verbatimModuleSyntax` yet, that's why the error.

I see 2 options:

1.  Continue with the suggested action from the error until vue fixes it from their end.
```
error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
  ```
  
 or 
 
 2. Drop the extending of `@vue/tsconfig/tsconfig.json` for our own tsconfig.

wdyt?

2023-05-15 06:30 UTC, closed without merging